spring:
  application:
    name: bookhub-backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/bookhub
    username: ${POSTGRES_USER:bookhub}
    password: ${POSTGRES_PASSWORD:bookhub}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

bookhub:
  greeting:
    message: "Bienvenue dans BookHub"
  environment: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bookhub: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: TRACE        # ← AJOUTER
    org.springframework.orm.jpa: DEBUG            # ← AJOUTER